---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 754406572667858945-QSnCSql9jY0tcIpjg6xACW3ZogqXwd9
:access_token_secret: ctMUGPfCB9bMrcHZmUlyusz00wh1sx6SKUEDBTYU2FpKq
